#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="dokku/$APP"
PORT="$(cat /home/dokku/$APP/PORT.web.1)"

/sbin/iptables -F
/sbin/iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port $2

echo "-----> Redirected port 80 to $2"
