#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="dokku/$APP"
PORT="$(cat /home/dokku/$APP/PORT.web.1)"
OLDPORT=0
if [ -e ~/plugins/dokku-single-app/$APP-current-port ]; then
	OLDPORT="$(cat ~/plugins/dokku-single-app/$APP-current-port)"
fi

if [ $OLDPORT -ne 0 ]; then
	>&2 echo "XXXXXXXXXXXX testing for rule existence"
	RULEEXISTS="$(/sbin/iptables -t nat -L | grep $OLDPORT)"
	>&2 echo "$RULEEXISTS"
	if [ -n $RULEEXISTS ]; then
		/sbin/iptables -t nat --delete PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port $OLDPORT
	fi
fi
/sbin/iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port $PORT

if [ ! -e "~/plugins/dokku-single-app/" ]; then
	mkdir -p ~/plugins/dokku-single-app/
fi
echo $PORT > ~/plugins/dokku-single-app/$APP-current-port

>&2 echo "-----> Redirected port :80 to :$PORT and removed old :$OLDPORT"
